### ISSUE TITLE
How to load the CIFAR data into python

### ISSUE THREAD

**Issue by w1malik** [dnlcrl/PyDatSet#1]
I have downloaded the CIFAR-10 data from http://www.cs.toronto.edu/~kriz/cifar.html and uncompressed it into my destination folder. By using the Python environment, the following codes are passed at first stage but found the problem in calling this data. I am newbie user please help.

import numpy as np
Xtr, Ytr, Xte, Yte = load_CIFAR10('data/cifar10/')

I found the below mentioned error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'load_CIFAR10' is not defined

**Comment by dnlcrl** [comment]
Hi malik,

firstly you should use the `get_CIFAR10_data` function instead of `load_CIFAR10`, anyway you should import the function before calling it.

Try adding `from pydatset.cifar10 import get_CIFAR10_data` after importing numpy.

You can also check [this file: https://github.com/dnlcrl/deep-residual-networks-pyfunt/blob/master/train.py](https://github.com/dnlcrl/deep-residual-networks-pyfunt/blob/master/train.py) to see how to load and augment the cifar10 dataset through pydatset.
